### ISSUE TITLE
MemberLogin not visible in DataType

### ISSUE THREAD

**Issue by Asadlerpwcom** [Mivaweb/MemberLogin#2]
I cannot add MemberLogin to the DataTypes as there is no property for this listed in the dropdown.

**Comment by Mivaweb** [comment]
Hi,

did you installed the package? Then when you go to the developer section > data types > add new datatype you should see the MemberLogin property editor.

Can you confirm that the folder MemberLogin is located under the App_plugins folder?

/Michaël
